on:
  pull_request:
    branches:
      - xxx[0-9]?
      - yyy[0-9]{4}
      - zzz[0-9]{4}(-[0-9]+)+

jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Hello, World!"
